version: '3.8'

services:
 flask:
   build: .
   ports:
     - "8000:8000"
   volumes:
     - "./flask:/opt/flask"
   tty: true
   environment:
     TZ: Asia/Tokyo
   command: flask run --host 0.0.0.0 --port 8000