version: '3'

services:
 flask:
   build: ./app/
   ports:
     - 5000:5000
   volumes:
     - ./app/src:/workdir
   # dbを構築してからwebを構築する
   depends_on:
     - db
   links:
     - db
   tty: true
   environment:
    TZ: Asia/Tokyo
    FLASK_DEBUG : "1"    #デバッグモードON
    FLASK_APP: 'run.py'         #起動用アプリの設定
   command: flask run -h 0.0.0.0

 db:
   build: ./mysql/
   volumes:
     - ./mysql/mysql_data:/var/lib/mysql # データの永続化
     - ./mysql/sqls:/docker-entrypoint-initdb.d # 初期データ投入
     - ./mysql/logs:/var/log/mysql
     #- ./mysql_data:/var/lib/mysql # MySQLデータベース保管場所
     #- ./init:/docker-entrypoint-initdb.d:ro # このディレクトリにあるsh/sqlファイルがコンテナup時に自動実行される
   environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=todo
     - MYSQL_USER=misato
     - MYSQL_PASSWORD=password
   ports:
     - 3306:3306
